description: Annual allowance for relief on pension contributions.
metadata:
  reference:
    href: https://www.gov.uk/tax-on-your-private-pension/annual-allowance
  unit: currency-GBP
values:
  2015-06-01:
    value: 40000
